defaults:
  - mujoco_single_traj
  - _self_

_target_: imitation_learning.datasets.mujoco_dataset.MujocoMultiTrajDataset

traj_num: ${eval:"${workspace.model.denoising_network_partial.max_history_len}+1"}
traj_interval_min: 8
traj_interval_max: 8


dataloader_cfg:
  batch_size: ${cond:${in:${policy_name},large},2,${cond:${in:${policy_name},rnn},8,4}}
  # RNN data is passed sequentially. Larger batch size is supported
  # For finetuning including the non-history modules. The actual batch size is 4 * 30 (traj_num) = 120


source_data_meta:
  action0_is_error:
    name: action0_is_error
    include_indices: ${range:0,16}
    shape: [1]

  action0_is_critical:
    name: action0_is_critical
    include_indices: ${range:0,16}
    shape: [1]

output_data_meta:
  action_is_error:
    name: action_is_error
    data_type: low_dim
    length: 16
    normalizer: identity
    augmentation: []
    shape: [1]
    source_entry_names:
      - action0_is_error

  action_is_critical:
    name: action_is_critical
    data_type: low_dim
    length: 16
    normalizer: identity
    augmentation: []
    shape: [1]
    source_entry_names:
      - action0_is_critical

split_dataloader_cfg:
  batch_size: ${cond:${in:${policy_name},large},12,32}
  num_workers: 12
  pin_memory: true
  persistent_workers: true
  shuffle: false
  prefetch_factor: 1

index_pool_size_per_episode: 100
starting_percentile_max: ???

repeat_dataset_num: 1 # How many times to repeat the dataset. Multi-traj dataset is comsumed much slower than single-traj dataset.