defaults:
  - _self_

dataset_type: mujoco

workspace:

  # Frame num stats: avg:  573.7, std:  46.6, max: 710, min: 546

  train_dataset:
    name: push_cube
    robot_num: 1  
    traj_num: 64
    repeat_dataset_num: ${cond:${in:${policy_name},memory,gated},1,5}
    starting_percentile_max:  ${cond:${in:${policy_name},memory,gated},0.4,1}

  model:
    memory_gate:
      image_encoder:
        image_meta: ${workspace.train_dataset.output_data_meta.third_person_camera}
      proprio_meta: ${workspace.train_dataset.output_data_meta.robot0_10d}
    denoising_network_partial:
      max_history_len: 30
      
  trainer:
    keep_saving_keywords: []
    num_epochs: 31